### ISSUE TITLE
Log outgoing emails in ElasticSearch

### ISSUE THREAD

**Issue by AnandChowdhary** [staart/api#1016]

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by AnandChowdhary** [comment]
This seems... unnecessary. I'm happy to reopen this if someone requires this feature, but I think most email services (SMTP or transactional, like Mailchimp) log outgoing emails themselves, so we don't need to implement that.
