### ISSUE TITLE
Confirm password before performing security tasks

### ISSUE THREAD

**Issue by AnandChowdhary** [staart/api#1023]
When performing actions like deleting your account, deleting your team, canceling a subscription, etc., the popup should ask for the user's password, and the API should check for `password`.

A helper function can be built and used:`@Middleware(ConfirmPassword)`

**Comment by mattpi-NSL** [comment]
Sounds like a great idea! :)

Out of interest how were you planning on 're authing' users who have logged in with Oauth to say Microsoft, new token grant?

Perhaps it would also be worth checking for TFA at this point if it is exists for that user or their org has enforced TFA (i.e to cover the 'enforced TFA since they logged in' case)?

**Comment by AnandChowdhary** [comment]
That's definitely food for thought. Apps like Stripe ask you to re-enter your password, and we can only do that if the user has a password set. If they don't have a password set and only use an OAuth login, we'll have to think of a better solution.

There are other apps that ask for the 2FA token instead of the password to confirm such actions, but I've noticed that users may be confused by this, and it's still better to stick to the password. Password managers also expect 2FA tokens with/after the password, not alone.

Lastly, I'm also planning on implementing a passwordless login system, where users who choose to can create an account without setting a password at all, and getting a new "magic link" on their email to login. In this case as well, we can't prompt for the password.

Perhaps:

1. If a user has a password set, prompt the password
2. If the user has 2FA set but no password, prompt the 2FA code

If they don't have either, we can:

1. Show them a modal saying they don't have either set, and it's recommended to have at least one every time they perform a security task?
2. If they have a phone number set, we can send them a 2FA code over SMS?
3. Send them a 2FA token or "magic link" to confirm their action over email?

**Comment by AnandChowdhary** [comment]
Even better, this can be a setting that the user can customize:

How do you want to confirm security tasks such as deleting your account?

1. Ask me for the password (selected by default)
2. Ask me for my 2FA code
3. Send me a magic link over email
4. Don't confirm (not recommended)

If they don't have a password or 2FA code, we can select option "3" by default, allowing users to set option "4" if they choose to.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
