### ISSUE TITLE
Admin View

### ISSUE THREAD

**Issue by mattp95** [staart/api#1034]
There is some mention of a super user login, from what I can see this seems to allow this user to login and access all 'teams' is that correct?

Is there any plan to create a admin dashboard where members of the team can view summery data and make changes on behalf of users?

**Comment by AnandChowdhary** [comment]
Yes, currently the superadmin can see a dashboard where they can see all server logs, teams, and users, and make changes to them.

**Comment by mattp95** [comment]
@AnandChowdhary Awesome, I assume this is done direct in the database as I am struggling to 
 see a API endpoint, I will add a PR to add this to docs and close this.

**Comment by AnandChowdhary** [comment]
That's correct. If the account type is admin, it will automatically show the relevant Admin UI in the webapp. :)

**Comment by AnandChowdhary** [comment]
@all-contributors, please add @mattp95  for documentation

**Comment by AnandChowdhary** [comment]
Reference: staart/staart.js.org#30

@all-contributors add @mattp95 for docs
