### ISSUE TITLE
API requests timing out (not returning JSON object)

### ISSUE THREAD

**Issue by simoami** [staart/api#1048]
@AnandChowdhary 
My requests are hanging. 
```
curl -X POST http://localhost:8080/v1/auth/login -H 'Content-Type: application/json' -d '{"email":"user@test.com","password":"..."}'
```
Not sure if this is work in progress for the migration to Nest, but currently returning payload causes requests to time out. Using the latest in master.

Overnightjs expects this response:
```
@Post()
private handler(req: Request, res: Response) {
  return res.status(200).json({
    message: 'test',
  });
}
```

but the current code returns the raw payload:
```
@Post()
private handler(req: Request, res: Response) {
  return {
    message: 'test',
  }
}
```

**Comment by AnandChowdhary** [comment]
Hi @simoami, this should not be the case, let me help you find what's not working here.

First, I'd like to make sure you're on the most recent version of Staart API. You can check that by making sure `"staart-version"` in your `package.json` is `"1.3.149"`. If this is not the case, you can update Staart API by entering `staart update api` in your console.

Then, make sure all dependencies are installed. We have several new dependencies that make sure the raw payload is processed as JSON and returned, so your example should be working. That logic comes from here: https://github.com/staart/packages/blob/master/packages/server/index.ts#L22 in package `@staart/scripts`. Make sure you've run `npm install` to get these new packages.

Can you please confirm you've this is all done, and then we can add some `console.log`s in your handler and see where this breaks down.

**Comment by simoami** [comment]
Hi @AnandChowdhary 
I pulled the latest update, wiped node_modules and reinstalled from scratch. It works with `yarn start`
However, I noticed my issue is with starting the server in debug mode in vs code. This config is what's causing the requests to stall:

launch.json
```
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "program": "${workspaceFolder}/dist/src/__staart.js",
      "preLaunchTask": "tsc: build - tsconfig.json",
      "outFiles": [
        "${workspaceFolder}/dist/**/*.js"
      ]
    }
  ]
```

Update: After removing the `preLaunchTask` line, it works. So I'm assuming the tarn build has more to it  than  just tsc compiling.

**Comment by AnandChowdhary** [comment]
That's correct, @simoami, the `yarn build` script does (much) more than `tsc`. It compiles TypeScript, generates controllers, appends middleware, and so on.

The script you want to run is `staart build`.

**Comment by simoami** [comment]
Thanks @AnandChowdhary 
For anyone else looking to run in debug more, here's the vscode config that worked for me:

.vscode/launch.json
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Debug",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "program": "${workspaceFolder}/dist/src/__staart.js",
      "preLaunchTask": "Build"
    }
  ]
}
```
.vscode/tasks.json
```
{
  "version": "2.0.0",
  "command": "tsc",
  "type": "shell",
  "tasks": [
    {
      "label": "Build",
      "type": "shell",
      "command": "yarn",
      "args": [
        "build"
      ],
    }
  ],
  "reveal": "always"
}
```
