### ISSUE TITLE
geolite2-redist 1.0.5 and above requires node 12 which is misaligned with staart

### ISSUE THREAD

**Issue by simoami** [staart/api#1071]
Here is the error during `yarn install` using Node 10:
```
error geolite2-redist@1.0.5: The engine "node" is incompatible with this module. Expected version ">= 12.10.0". Got "10.19.0"
```

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @simoami!

You're right, it seems like Staart API's dependency `geolite2-redist` requires Node.js v12.x, whereas Staart API works with 10.x (except for this dependency).

I can update Staart API's minimum Node.js version to 12.x, though I don't see why `geolite2-redist` cannot work with Node.js 10.x, I don't think it has any 12.x-specific features. I'll open an issue there.

**Comment by simoami** [comment]
While this is easy to fix, I just wanted to give you a heads up so that users of staart continue to have a smooth experience.

Also, here's the commit where they bumped it:
https://github.com/GitSquared/node-geolite2-redist/commit/57af0bec54133e17325204c271ad5402d5b65f5d

Not sure what mandates an engine bump though  :)

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by AnandChowdhary** [comment]
This is fixed in v3.
