### ISSUE TITLE
Update Staart API and UI demo sites

### ISSUE THREAD

**Issue by dnordberg** [staart/api#1081]
I get the following error:

![image](https://user-images.githubusercontent.com/15315/78614663-d6e51480-7877-11ea-9ba8-c18e357da612.png)

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by AnandChowdhary** [comment]
I'm keeping this issue open until I deploy the new Staart API and UI demos.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
