### ISSUE TITLE
REFERRER_CHECK_FAIL error verifying JWT token

### ISSUE THREAD

**Issue by dnordberg** [staart/api#1110]
Release: 1.0.130

I get an error REFERRER_CHECK_FAIL error when verifying the JWT Token.

Contents of `apiKeyToken.referrerRestrictions`:

0:"staart-demo.o15y.com"
1:"localhost"
2:"oswaldlabs.com"
3:"staart-ui.o15y.now.sh"

It tries to match 127.0.0.1 but fails.

What I don't understand is how and where these are set, since I can't find them searching the codebase.

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @dnordberg! These are part of the API key you're using in the frontend. This will go away if you remove the Axios API key: https://staart.js.org/ui/getting-started (under "Frontend API key")
