### ISSUE TITLE
Default .env.example inline comments causing malformed links and values.

### ISSUE THREAD

**Issue by WTM-Jarryd** [staart/api#1126]
Hi Anand,

The inline comments within the **.env.example** file cause issues with the assigned values due to **dotenv** evaluating the comment as part of the value.
e.g. `FRONTEND_URL = "http://localhost:3000" # URL for Staart UI`
evaluates to
`FRONTEND_URL: "http://localhost:3000" # URL for Staart UI`

This causes issues later when emails containing links to **{{frontendUrl}}**, as they will all have the above evaluated value.

A note should be added to the [https://staart.js.org/api/setting-up-environment-variables](https://staart.js.org/api/setting-up-environment-variables) documentation stating that comments should be on their own lines.

Edit: Removed an incorrect note about **dotenv** not supporting comments. Comments are marked with #

[env.example.txt](https://github.com/staart/api/files/4564008/env.example.txt)
I've attached an .env.example with all the inline comments shifted to the line above the value they are describing.

Kind regards,
Jarryd

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @WTM-Jarryd! I didn't know dotenv required comments to start with a new line, I'll fix the example soon!

**Comment by WTM-Jarryd** [comment]
dotenv doesn't handle comments at all actually.
This is something they should maybe look into, but it doesn't cause compilation or runtime errors.
Doing a `require('dotenv').config({ debug: true });` will just alert with a warning on the comment lines.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by AnandChowdhary** [comment]
This is fixed in v3.
