### ISSUE TITLE
Add features to admin dashboard about server info

### ISSUE THREAD

**Issue by AnandChowdhary** [staart/api#1142]
- [x] Show a list of all users and teams
- [x] Server logs from ElasticSearch
- [x] List and create coupon codes
- [ ] Clear Redis, either completely flush or `del` by key
- [ ] Show IP address, other server details
- [x] Payment logs from Stripe
- [ ] Show `htop`-style server status for resources?

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by AnandChowdhary** [comment]
We now have the Metrics module.
