### ISSUE TITLE
Typescript will not compile

### ISSUE THREAD

**Issue by PrometheusGlobal** [staart/api#1352]
Keep getting
error TS6053: File '.staart/**/*.ts' not found.
on build
with version 1.0.0

After looking at .staart/src/app.ts further the build script is creating the links to the controllers like:

import { AdminController as Controller0 } from "./controllers\admin\index";
import { AuthController as Controller1 } from "./controllers\auth\index";
import { UserController as Controller2 } from "./controllers\user\index";
import { WebhooksController as Controller3 } from "./controllers\webhooks\index";
import { OrganizationController as Controller4 } from "./controllers\organization\index";import { ChildControllers } from "@staart/server";

instead of:

import { AdminController as Controller0 } from "./controllers/admin/index";
import { AuthController as Controller1 } from "./controllers/auth/index";
import { UserController as Controller2 } from "./controllers/user/index";
import { WebhooksController as Controller3 } from "./controllers/webhooks/index";
import { OrganizationController as Controller4 } from "./controllers/organization/index";import { ChildControllers } from "@staart/server";

**Comment by AnandChowdhary** [comment]
Are you using Windows?

**Comment by PrometheusGlobal** [comment]
I was but started a fresh ubuntu server ran install as normal, tried to run build came up with an @types/regenerator-runtime module error, installed it via npmjs, ran build again build looked like it ran fine. Upon running start getting warning on Database unable to run query 'SHOW tables' running mysql 8 and warning on Elastic Search saying missing AWS credentials even after i set them up in the .env file.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by AnandChowdhary** [comment]
This is now fixed in v3.
