### ISSUE TITLE
For anyone having issues with Prisma

### ISSUE THREAD

**Issue by PrometheusGlobal** [staart/api#1380]
NOTE THIS HAS ONLY BEEN TESTED ON 2.18 AND ONLY DOWN TO WHEN PRISMA WAS INTRODUCED!!

once you install the API package here are a few things to do to make your life a little easier.

go under your prisma directory and create a .env file with a connection string that looks like this.
DATABASE_URL=mysql://USER:PASSWORD@HOST:PORT/DATABASE

then run:  npx prisma migrate up --experimental

once you have that done before you run build there are a few changes that you need to make

1.  In  node_modules/@staart/scripts/lib/commands/build.js

look for: shelljs_1.cp(".env", ".staart/prisma/.env");     change this to  shelljs_1.cp("./prisma/.env", ".staart/prisma/.env");
it will now refrence the .env file you created in the prisma directory

2.  Run build it will give an error abour not finding the .env file we will fix that in a moment

3. after running build for the first time look in your .staart directory and create a new directory called prisma
    under the new prisma directory create a blank .env file

4. Run build again and then you should be able to run start with no issues

**Comment by AnandChowdhary** [comment]
I'll make sure Prisma is handled properly in the docs! You're right, the `.env` file needs to be in `prisma`, but I'll also set up this in the build process. I'll keep this issue open until we're there!

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by AnandChowdhary** [comment]
This has now been updated in a new release of Prisma and fixed in v3. You can set your database configuration in the root `.env`.
