### ISSUE TITLE
Please update and correct the documenation

### ISSUE THREAD

**Issue by johnnynanjiang** [staart/api#1382]
It looks like the doc is not update-to-date with the codebase.

1. There is `node dist/src/index.js` in the documentation https://staart.js.org/api/getting-started.html, but the file index.js is missing in `dist/src` folder.

2. The sample API code is outdated at https://staart.js.org/api/creating-a-controller.html, probably a sample endpoint could be included in the codebase so it will always update-to-date and work?

Good documentations would be a great help for people to try out this awesome product.

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @johnnynanjiang! You're absolutely right. I'm currently working on `master`, adding an easier way for people to get started (better configuration management), and my goal is to re-write the entire docs site with comprehensive examples. I'm keeping this issue open to update you.

**Comment by johnnynanjiang** [comment]
> Thanks for opening this issue, @johnnynanjiang! You're absolutely right. I'm currently working on `master`, adding an easier way for people to get started (better configuration management), and my goal is to re-write the entire docs site with comprehensive examples. I'm keeping this issue open to update you.

Hi Anand, thanks for doing that, I believe good documents would save developers a lot of time.

For example, we just found out that we need to add `v1` in URI to access endpoints like `http://localhost/v1/...`, things like this wasted us a lot of time, and is missing from the documentation.

I think code is the best documentation, including a working sample endpoint in the codebase would solve the problem easily.

**Comment by AnandChowdhary** [comment]
I've started working on this! Hopefully this will turn into comprehensive docs for everyone: https://github.com/staart/api/tree/master/docs.
