### ISSUE TITLE
App crashes if Redis is not available

### ISSUE THREAD

**Issue by johnnynanjiang** [staart/api#1406]
We had a nodejs service based on Staart, and it kept crash down on AWS for a week. It turned out to be Redis is missing. It still could go up and running without Redis, but just crashed from time to time.

**Comment by AnandChowdhary** [comment]
Redis is an important component because it helps not only with caching, but also with token invalidation (very important for authentication). You can either use AWS-manages Redis (https://aws.amazon.com/elasticache/) or just run your own `redis-server` before starting the app. 😄

**Comment by AnandChowdhary** [comment]
This is now fixed in v3. You don't need Redis anymore, as we don't invalidate JWTs (refresh tokens are UUIDs and require a database request, rather than being JWTs that need to be invalidated).
