### ISSUE TITLE
Can not add payment method from ui

### ISSUE THREAD

**Issue by WaysonWei** [staart/api#1428]
Firstly, thank you for open sourcing this amazing  saas start kit. We still not able to run latest API & UI ( V2 ? )together at this point, but would be able to run them together with API v1.0.0 & Ui v1.0.0. 

Now facing this issue. Not able to add payment method via UI showed as screenshot. Look like it is something to do with API regarding organization endpoint? 

![Screen Shot 2020-10-09 at 10 41 01 AM](https://user-images.githubusercontent.com/54336863/95517054-c5deb100-0a1c-11eb-8f6b-f3ec7fee7e49.png)

**Comment by WaysonWei** [comment]
I had it sorted... The API backend sending the credit card number directly to Stripe API, that's why showing 500 error. We need to use the token instead of the card number.

**Comment by AnandChowdhary** [comment]
Thanks! If this is a bug not related to your use case but to Staart API, would you like to make a PR?

**Comment by WaysonWei** [comment]
This issue is not relate to the bug of Staart API. In this case, Stripe recommended to wrap the customer payment details with Stripe Element and the new API rather than sending the raw credit card number directly to Stripe's API.  We will be working on the payment code to make it working smoothly, will submit a PR if we come across any. Thanks again for this amazing project.
