### ISSUE TITLE
2 Questions :: 

### ISSUE THREAD

**Issue by FELS-Zak** [staart/api#1477]
Hi - 
Just 2 quick questions please
1 - Is this totally free and access to full source code 
2 - Where is the demo site?

**Comment by FELS-Zak** [comment]
👍

**Comment by gurisko** [comment]
1. License can be found [here](https://github.com/staart/api/blob/master/LICENSE)
2. You can find your answer in the [README](https://github.com/staart/api#-docs). However the API seems to be offline at the moment. You can also have a look at section "Built with Staart"

**Comment by FELS-Zak** [comment]
Thank you- 
What have you built with this so far?

**Comment by AnandChowdhary** [comment]
Thanks for answering, @gurisko! Yes, the demo API is down, I'll make sure I put it back up soon! You're right, it's licensed under the permissive MIT, meaning you can do whatever you want with Staart API. I personally have built several Staart API-based systems for my friends at accessibility technology company [Oswald Labs](https://github.com/OswaldLabsOpenSource/platform-v3], interior design subscription [Koj](https://github.com/koj-co), VoIP/text communication API [Speakup](https://github.com/speakupnl/staart), email assistant [EIVA](https://github.com/o15y/eiva), among others.

**Comment by AnandChowdhary** [comment]
I'll keep #1081 open to make sure I remember to bring the demo API back online!

**Comment by FELS-Zak** [comment]
Thank you
