### ISSUE TITLE
how to setup v3 

### ISSUE THREAD

**Issue by aubeena007** [staart/api#1593]
thanks for the framework . so exited to test it out. but i cannot found docs for v3 default readme is for v2 i think.
any quick guild to get setup in local

**Comment by rjain15** [comment]
What is changing in v3, and can I get started using the v2 doc?

**Comment by deephut** [comment]
Definitely seems like it needs some updating, for example if you set up the ui repository and api, register an user where it displays the onboarding info, it tries to PUT/POST to a route that doesn't exist.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
