### ISSUE TITLE
Return created objects

### ISSUE THREAD

**Issue by AnandChowdhary** [staart/api#16]
As per the suggestion of @victorlap, methods which create a new organization/user/membership/etc., should return the newly created object.

This, combined with the right HTTP status code `201`, can be better than just returning `{ created: true }`.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by AnandChowdhary** [comment]
This is now fixed in v3.
