### ISSUE TITLE
Docker does not expose ports needed for frontend to connect with backend

### ISSUE THREAD

**Issue by deephut** [staart/api#1619]
Seems maybe it's outdated or I'm doing something wrong?
I builded the dockerfile with
`docker build -t api`
and then proceeded with` docker run api` 
Which doesn't load the API  page, at all.
As seeing on frontend, the backend port should be 7007 - so I also tried to expose the ports in docker, like so:
`docker run -d api -p 7007:7007`
this kind of loads the api page, but the response is empty, any ideas or tips?

**Comment by AnandChowdhary** [comment]
This is now fixed in the Dockerfile. On production, you'll be running on port `80` so that's exposed. The `7007` is just an arbitrary port for development, so we can ignore that. 😄
