### ISSUE TITLE
Outdated endpoints?

### ISSUE THREAD

**Issue by kuttim** [staart/api#1626]
I'm getting alot of unauthorized/not found errors with requests to backend from my frontend, is this something already addressed or is the issue on my side only?
![Image of error](https://i.ibb.co/Qbh6wrq/errors.png)

**Comment by kaivanmehta14** [comment]
It seems like you are accessing users controller without any login/register, all other controllers are protected so you cannot access them directly without login. also put request in groups controller expects some group id. hope it helps

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
