### ISSUE TITLE
Error - geolocation.service.spec.ts

### ISSUE THREAD

**Issue by zaratt** [staart/api#1734]
Hello
First, congratulations on the template, very good.
I have an error when I run **npm run test: unit**
It shows an error as shown in the figure below.
The stranger who was ok, but just started giving this error.
P.S .: Do you have any contact e-mail?

Thanks
![Captura de Tela 2021-02-13 às 21 55 00](https://user-images.githubusercontent.com/22323892/107865696-083f5100-6e48-11eb-85ff-f1a6ca8a7dcc.png)

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by AnandChowdhary** [comment]
Looks like the GeoIP2 database was not downloaded, which is typically in the `postinstall` script of the `geoip2-redist` package. You can do that manually as well: https://github.com/GitSquared/node-geolite2-redist/blob/v1.0.7/scripts/postinstall.js

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
