### ISSUE TITLE
MySQL: ER_NOT_SUPPORTED_AUTH_MODE

### ISSUE THREAD

**Issue by ektek** [staart/api#277]
Leaving this for any user who comes across this (using MySQL 8.0=<). Be aware that the backend might throw the following error:

```
Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
```

You'll have to switch over to `mysql_native_password`

```
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
FLUSH PRIVILEGES;
```

**Comment by AnandChowdhary** [comment]
Hi @ektek, can you perhaps add this to https://staart.js.org/backend, maybe creating a "Database configuration" file? This way I can close the issue and we'll have it on the docs website. 

https://github.com/staart/staart.js.org

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
