### ISSUE TITLE
Implementing/Using a Reseller Model

### ISSUE THREAD

**Issue by mattp95** [staart/api#332]
Hi there,

I am working on extending some business logic so that resellers can be supported. In this case a Reseller can create a org, invite the end customer to be the org owner and then the reseller picks up the bill with billing disabled for the end user. 

I noticed references to the naming of a role as reseller. I am curious if others are already doing something similar are if there are plans to build in reseller logic and roles which I can work on rather than starting from scratch.

**Comment by AnandChowdhary** [comment]
Hi @mattp95, thanks for opening this issue!

You're right, the reseller part is still in todo stage. I definitely have plans to complete this within September 2019.

Right now, reseller is only a membership type, but it will be equivalent to owner and will be able to add/remove users, change settings, etc. Furthermore, the reseller will also be able to get a commission for their clients (say 10% of your revenue goes to the reseller), and we'll integrate Stripe Connect to automate payouts as well. All of this is todo.

In your case, perhaps you can customize Staart to do something like "if a reseller exists for this organization, disable billing for all other users". Unfortunately, you'll have to wait for me to add the aforementioned logic before you'll be able to customize that.

**Comment by AnandChowdhary** [comment]
In any case, @all-contributors, can you please add @mattp95 in bugs?

**Comment by mattpi-NSL** [comment]
Thank you for this. I will hold back on working on this part for a bit then. Maybe I can add a PR for my model too so there is maximum choice on the business model of dealing with resellers.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
