### ISSUE TITLE
Use Casbin to manage user permissions 

### ISSUE THREAD

**Issue by MP70** [staart/api#337]
Hi @AnandChowdhary ,

At the moment the permissions hierarchy isn't well enforced as for example: when creating a new user on a organisation a manager can create an owner - so at any point anyone with permissions to CRUD team members can escalate themselves to owner by inviting one of their other email addresses. Would it be a reasonable idea to add some logic which says that users can only invite new members to a team with a permission level of lower than their own permission level, unless they are a team owner in which case that logic doesn't apply (i.e they can create other owners too)? This would mean say.. a business owner authorises/creates all new manager accounts, a manager authorises/creates all new 'basic employee' accounts? A business owner can add other business owners as they see fit, but a manager cannot add another manager or escalate himself or others to owner.

Also the edit member ui on that page is broken, I was thinking of coming back to that after I discussed the permissions with you.

**Comment by mattpi-NSL** [comment]
Taking another look, perhaps using casbin (https://github.com/casbin/node-casbin) preferably or https://github.com/onury/accesscontrol#guide as a framework for managing this RBAC is a more flexible  approach?

**Comment by AnandChowdhary** [comment]
@mattpi-NSL, using Casbin is a great idea! It's far superior to the current hard-coded authorization helper, and it's much more scalable and customizable. Let's put this on the project!

**Comment by MP70** [comment]
I have taken a look a bit further down this path. For now in my branch I am using Postgres for the database, I notice this master branch is now using Prisma. Casbin has adapters for Knex/Sequelize/TypeORM as SQL ORMs as well as for psql and mysql however it doesn't have one for prisma. I think this may mean that we need to write an adapter for Prisma or (re)use Redis for this.

**Comment by hsluoyz** [comment]
Hi @AnandChowdhary @MP70 I'm from Casbin team. We have made a Prisma adapter these days: https://github.com/node-casbin/prisma-adapter . Can you try it?

**Comment by MP70** [comment]
Wow! Thank you so much, this is incredible! My fork has diverged quite a lot from this and I am using different set of technologies, so I will leave this to @AnandChowdhary for now, but if he doesn't get to it first as soon as I have some free time I will definitely take a look at this!

**Comment by AnandChowdhary** [comment]
> Can you try it?

This looks great, thanks for all your hard work, @hsluoyz! I'll definitely have a look at this, because now it fits right into our Prisma-led database framework and would be much easier to adopt.

**Comment by AnandChowdhary** [comment]
Good news! After many months, this is now shipped in `master`! 😄

Default policy model: https://github.com/staart/api/blob/master/casbin-model.conf
Updated authorization helper, built with Casbin: https://github.com/staart/api/blob/master/src/_staart/helpers/authorization.ts

**Comment by hsluoyz** [comment]
Thanks! It's great work!
