### ISSUE TITLE
Install on Ubuntu is failing at "npm run build"

### ISSUE THREAD

**Issue by smart-reports** [staart/api#711]
hello

I've tried to install.  First the use my template buttom gave an error about files being more than 10mb so I downloaded to my desktop and went through the manual process to get it setup;

I get this error though and npm run build stage.  Any ideas?

root@staartsaas:/srv/staartapp# sudo npm run build

> smartstaart@1.2.2 build /srv/staartapp
> touch .env && mkdir -p dist && cp .env dist/.env && npm run generate-routes && tsc && cp -r lfs dist/src

> staartapp@1.2.2 generate-routes /srv/staartapp
> node setup/controllers.js

✖  error     Error in setup [Error: ENOENT: no such file or directory, scandir '/srv/staartapp/src/controllers'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/srv/staartapp/src/controllers'
}

**Comment by AnandChowdhary** [comment]
Seems like the directory `./src/controllers` doesn't exist. Can you make sure all the controllers are there, like in this directory [src/controllers](https://github.com/staart/api/tree/master/src/controllers)? Maybe there was an error in cloning the repository and some files were missed?

**Comment by smart-reports** [comment]
> Seems like the directory `./src/controllers` doesn't exist. Can you make sure all the controllers are there, like in this directory [src/controllers](https://github.com/staart/api/tree/master/src/controllers)? Maybe there was an error in cloning the repository and some files were missed?

In /src/controllers there is a folder called v1 - no files?

**Comment by AnandChowdhary** [comment]
That's right, and the `v1` folder should contain all your controllers. This would translate your API endpoints to be, for example, https://example.com/v1/user.

Since the error says `no such file or directory, scandir '/srv/staartapp/src/controllers'`, can you see if the following command shows you the list of files?

```bash
cd /srv/staartapp/src/controllers
```

**Comment by smart-reports** [comment]
> ```shell
> cd /srv/staartapp/src/controllers && ls
> ```

hmmm - I should have checked.  I'm sorry, my files didn't seem to sync fully on my server :redface:

**Comment by AnandChowdhary** [comment]
Best of luck! Let me know if you have any trouble and I'll be happy to help. 😄

**Comment by smart-reports** [comment]
Hi there

Finally got all the files now.

Have you experienced this before?  Its stuck on building....specifically Compiling TypeScript.....

does the app need a certain amount of RAM?  I stuck it on a cheap digital ocean server just to test it.

> node setup/controllers.js

✔  success   Generated paths
✔  success   Processed no redirect rules
✔  success   Setup 3 cron jobs
✔  success   Serving 2 static files
✔  success   Generated app.ts file
☐  pending   Compiling TypeScript

**Comment by AnandChowdhary** [comment]
No, I haven't seen this before. It seems like the `tsc` process is not finishing for you. I'll purchase a Digital Ocean $5 droplet and see if I can reproduce your error.

**Comment by smart-reports** [comment]
> No, I haven't seen this before. It seems like the `tsc` process is not finishing for you. I'll purchase a Digital Ocean $5 droplet and see if I can reproduce your error.

I upgraded the server and still same outcome.  Now its got:

2 GB Memory / 60 GB Disk / LON1 - Ubuntu 19.10 x64

**Comment by smart-reports** [comment]
> > No, I haven't seen this before. It seems like the `tsc` process is not finishing for you. I'll purchase a Digital Ocean $5 droplet and see if I can reproduce your error.
> 
> I upgraded the server and still same outcome. Now its got:
> 
> 2 GB Memory / 60 GB Disk / LON1 - Ubuntu 19.10 x64

Ok so I did this:

sudo chmod 777 /srv/staartapp
rm -rf node_modules && npm install

It seems to have gone further this time which is an issue with the email....never used Amazon SES before so maybe got something wrong in my setup.

Thanks for your help Anand.
