### ISSUE TITLE
Ability to merge accounts

### ISSUE THREAD

**Issue by simoami** [staart/api#950]
Hi @AnandChowdhary 
Thanks for your great implementation! One area I was wondering about is the ability to merge 2 user accounts belonging to the same user. There are 2 scenarios in which a merge can apply.

### 1. Before joining an invite
You already have this covered through the email record resolution.
### 2. After joining an invite
Two or more user records would have been created by then. so it would be great to have to ability to allow the user to merge into one of the user records.

Coincidentally, I found a saas app with similar concept but I'm not convinced that their approach works in consolidating user data. From their steps, I guess they only map an email back to the first user. But that still leave the second user as a disconnected record.

https://help.clubhouse.io/hc/en-us/articles/211154966-Merging-User-Accounts-in-Clubhouse

Would love to hear your thoughts!

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @simoami. I'd love to explore what this might look like, but I'm having trouble understanding how there will be two accounts in the first place.

Currently, and this is from my memory but could be wrong, you can invite a member to your team regardless of whether they already have an account or not. If they don't, we'll create a new account and send them an email. If they do, we'll just use that account and not create another one.

Can you help me understand what you mean by "After joining an invite" and having two or more user records?

**Comment by simoami** [comment]
Sure I'll try to explain.
Imagine the saas app also evolves to also allow users to manage projects. and a user is allowed to see the projects they own via table `projects.userId`

now to the invite scenarios:
### 1. Scenario One (the happy path)
I sign up as `User A` with `Email A` and create `Organization A`. I add `Email B` anticipating `Organization B` will invite me. When `Organization B` invites me using `Email B` as expected, Staart sees that `Email B` is already in the system and is mapped to `User A`. Staart then adds a membership record for `User A` to `Organization B`. Additionally, when `User A` switches between any of the orgs, he or she can see the projects they own for that organization.

**Outcome:**
We have a single `User A` record. When `User A` logs in, he or she sees 2 organizations in the Profile menu! Great!

### 1. Scenario Two
I sign up as `User A` with `Email A` and create `Organization A`. `Organization B` invites me using `Email B` (before I got a chance to add Email B as alias), Staart sees that `Email B` doesn't exist in the system and creates `User B`. Staart then adds a membership record for `User B` to `Organization B`. See attached diagram for illustration. 

**Outcome:**
We now have 2 record representing the same user: User A and User B. When User A or User B logs in, he or she doesn't sees 2 organizations in the Profile menu! In this scenario, The user would like to have easily switch between Orgs without going through the log out as User A and log back in as User B and vice versa. Imagine a scenario where this happens with 10 orgs inviting the same accountant. Most orgs would assign contractors a new email under their domain to keep communication secure. And it would be great to have access to these under the same login credentials.

The process outlined in the link I shared suggests remapping Email B to User A and have User B use a temporary alias `eg. EmailB+old@OrganizationB.com` as primary email. That works, from a login perspective but the memberships and project ownership for User B won't change as a result of this trick.

I'm guessing we would need to think of a workflow to offer an account reconciliation process. 

<img width="786" alt="Screen Shot 2020-02-24 at 12 29 21 PM" src="https://user-images.githubusercontent.com/2038264/75176217-c3378180-5701-11ea-97a5-fd7eda0f6cfd.png">

**Comment by AnandChowdhary** [comment]
Aah, I understand now! I'm very used to quickly adding all my emails whenever I create an account so this type of thing never happens, so I didn't think about it at all! I think this is a very important feature to ship in Staart because I can easily imagine people adding a personal email and then getting invited to their work account.

Here are some options off the top of my head:

1. We don't create a user when an invite goes, only a "hollow" membership with the invited user's name and email, and when they click on the "Activate" link in the email, the UI lets them choose whether they want to create a new account or use an existing account.
2. We do create that new account (like we do currently), and add an option in the settings UI to "connect" two accounts; in this case, people can enter the email of the other account, and we'll join them into a single account.

I think we can either do only option (2), or both option (1) and (2), but that adds another level of complexity to the onboarding process for new invited users.

Any other ideas?

**Comment by AnandChowdhary** [comment]
By the way, @simoami, this is such a well-thought of and informative flowchart to showcase how Staart API does membership invitations. Do you mind if I end up using this somewhere in the docs? I'm happy to add you as a contributor for your hard work!

@all-contributors please add @simoami for ideas, docs

**Comment by simoami** [comment]
Great options!
I think that option 2 is the least involved in that it keeps the current logic intact. I also favor option B in this case because there will always be other edge cases where the user neglects to log in to maintain the same user account but later want to merge the 2 accounts.

Re: Thanks regarding the chart.  Attaching the draw.io source file:

[staart - flows.drawio.zip](https://github.com/staart/api/files/4245997/staart.-.flows.drawio.zip)

**Comment by AnandChowdhary** [comment]
Great, I'll implement this and push a Staart API update within the next couple of days!

**Comment by simoami** [comment]
btw, some food for thoughts.
upon login, add can check cookies to see if the user ever signed in using a different account. in this case we could prompt the user with "Hey, looks like you have signed in to a different account in the past using 'xxx@xxx.com`. would you like to merge the  2 accounts?`
Selecting Yes lead to the merge view where you are presented with 2 options:
1. Merge another account into this one, delete the other account
2. Merge this account onto the other account. 

I assume # 2 would just prompt you to log out and log back in to the other account because you don't want to delete an account when the user is currently logged in with it. 

I would do some google search into account reconciliation to see how others present it from a UX perspective.

**Comment by simoami** [comment]
Also, if users of staart end up extending the api to include other entities with the userId reference, it would be good to have a hook where they can also complement the migration by updating the userId references. maybe an optional handler with oldUserId, newUserId and they can supply with their own loagic.

**Comment by AnandChowdhary** [comment]
> maybe an optional handler with oldUserId, newUserId and they can supply with their own logic

Yes, this makes sense, and I want an easy way to see older versions of an account linked together, but `oldUserId` doesn't work because there may be any number of older user IDs, for example if you're invited to multiple organizes and therefore connect all of those accounts together.

I'll keep this issue posted with the progress.

**Comment by simoami** [comment]
Thank you.
I would also prompt the user for the password to the other account to
ensure they own it. I leave it up to you to decide what to do if the other
account has 2FA enabled.

**Comment by simoami** [comment]
Some more thoughts:
1. The reconciliation process can also be triggered when a new email alia is added and the email address belongs to  an existing user. With the correct http response (http 409 conflict), the UI client can suggest to migrate the other account the email address belongs to. 
2. As part of the reconciliation, all email aliases from user B are moved to user A in their current state (verified or not)
3. Do we restrict this logic to just primary/verified email addresses on the other accounts?
