### ISSUE TITLE
Use caching library instead of Redis

### ISSUE THREAD

**Issue by AnandChowdhary** [staart/api#964]
Use a Node.js caching library (like node-cache or node-cache-manager) for JWT invalidation, etc., instead of Redis directly, with Redis as the primary kv-store with in-memory as fallback

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by AnandChowdhary** [comment]
This is now fixed in v3. We use `quick-lru` and `mem`.
