### ISSUE TITLE
Add OpenAPI/Swagger support

### ISSUE THREAD

**Issue by AnandChowdhary** [staart/api#966]
Parse controllers for `joiValidate` functions, HTTP verbs, and TypeDoc comments to generate a schema

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by AnandChowdhary** [comment]
This is added in v3.
